### ISSUE TITLE
Rationalize kv/db abstractions

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#22]
Concrete problems:

- In several places the entire map is read from Noms to compute the initial checksum
- In the call stacks to store and read data, we go back and forth between Noms/JSON several times
- kv doesn't support `Has` or `Scan` operations that client code needs
- In the client `db` has an `editor` and so does `Map` and they do almost the same thing, the only reason the former is needed is because of lacking `Has` support.

Subjective problems:

- `kv` presents an abstraction of a persistent kv map that hides implementation details, e.g., Noms. However Noms is not completely hidden from caller (`db`) because db is still responsible for all the commiting and other machinery of Noms. So it seems to me that the main benefit of `kv` is not attained in its current form. An abstraction that was more complete seems like it would just look like`db`.
- Abstracting away the impl detail of Noms is not a requirement that we have right now. Although we think we might use something other than Noms on the client, (a) in that universe we'd also not likely use Go, obviating the need for the abstraction, (b) if we did need it in the future, we could just do it then, when we had more information.

**Comment by phritz** [comment]
couple of questions. 

first thing, the goal of kv was not so much to hide the implementation detail of noms, it was to encapsulate important business logic and to present an abstraction that cannot be mis-used. we talked about if you let callers work directly with noms maps they could violate some invariant, like updating the checksum or setting uncanonicalized values. clearly as you pointed out we could instead enforce invariants and apply business logic at save time instead of at operation time and that may be a good tradeoff. anyway, the trajectory kv.map was on was to replace the noms map occurrences in the public interfaces of db with this new map that encapsulates our business logic so that's what callers work with. if the code had gotten there, say map and friends moved into db and was the map thingy that callers worked with, would that have worked to at least partially address the first subjective issue, assuming the details made sense?

second question: we had talked about removing noms from the client api and having it work with string keys and byte slice or map[string]interface{} values. and that we should talk about whether that made sense to do at a lower level as well. is removing noms from the client api still a thing you think we should do?
