### ISSUE TITLE
mutate() - write transactions

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#28]
This bug builds on #27 to add mutations.

# Overview

```dart
var rep = Replicache(...);

var createTodo = rep.register('create-todo',
  (WriteTransaction tx, dynamic args) async {
    var id = args['id'];
    var listId = args['listId'];
    var text = args['text'];
    var complete = args['complete'];
    var key = '/todo/$id';
    if (!await tx.has(key)) {
      await tx.put('/list/$listId', {
        title: 'Untitled List',
      });
    }
    await tx.put('/todo/$id', {'text': text, 'order': order, 'complete': complete});
  },
);

// Modifies the cache locally and queues the remote write for next sync.
await createTodo({
  'id': uuid.new(),
  'listId': 42,
  'text': 'Take out the trash',
  'order': 0.5,
  'complete': false,
});
```

# Concurrency

The local half of mutations execute against the cache using optimistic locking of the entire cache provided by the underlying Noms database. If the optimistic lock fails, the mutation is retried internally until the optimistic lock succeeds.

There should be some limit to the number of times a transaction will be retried to prevent degenerate iloop cases. Maybe 10?

# Details

* The result of executing a mutation is a new *pending* transaction in the underlying Noms database that records the mutation name and args
* During sync, Replicache may re-execute registered transactions by name. Users must ensure that any registered transactions are registered across application sessions.

**Comment by arv** [comment]
As I mentioned elsewhere, the strawman API is not doable in Dart due to its limitations.

My plan is to provide something more low level and see what patterns evolve around that once we have some sample apps.

**Comment by phritz** [comment]
i'm about to get started thinking about #30 and to do so i need to better understand what is happening in this issue. here's how i think this might work, please tell me what i have wrong or am missing:
- there is a registry of transaction implementations identified by name in bindingsland. customers register tx implementations on this registry and implementations are always available and never change once registered. there must exist a corresponding implementation by that name in the data layer. the registry might be stored anywhere including in noms (?), but that is not essential or relied upon by repm, the client, or protocol.
- when bindings calls opentransaction for a mutation it supplies the transaction name and arguments used which are kept in the db.Transaction while it is executing. the caller does its thing, calling put/get/has/etc against its Transaction. when the caller calls committransaction the Transaction writes its Commit which includes the name and args. commit must also record the transaction id so during sync we know which transactions have already been applied.
- all tx commits following the most recent genesis commit are pending. it does not appear that we need store anything separately.

Is that about right? If so, question:
- the system supplied transactions .putvalue/.delvalue seem to exist to support command line transactions that dont have a registry to supply an implementation. they kind of complicate the mental model though: the bindings have to know to treat these special transactions differently from transactions they have registered and has to disallow transactions with these names. is there any way we could eliminate them so that all transactions are treated the same? like for example automatically register put/del as transactions in the registry? if command line put/del is important we could always require that the registry have those transactions and then continue to do them manually in the put/del command line implementation (create a Transaction and call put/del on it).

**Comment by aboodman** [comment]
> there is a registry of transaction implementations identified by name in bindingsland. customers register tx implementations on this registry and implementations are always available and never change once registered.

It's not true that they never change, and it's important to be clear about this.

 It's a feature that the impls can and will change (e.g., to fix bugs, cope with schema changes, etc). The concept is that the name and args are a *signature* or *interface*. Replicache is effectively keeping a history of events, where each event is a function name and args.

User code provides the local (and remote, for that matter) implementations of these functions. Replicache will periodically call both the local and remote impls for a variety of reasons.

I think that repm (the client) should tolerate missing implementations, because otherwise the product is hard to use (it would be easy to ship a release that accidentally removed an impl and then that client would be wedged until fixed). But that is a value judgement. It could work either way. Another way to say that is that repm will provide a no-op impl of any missing functions on the client-side, and will log an error.

On the server, the server *must* acknowledge all writes. It can of course do a no-op on its side, but it can't just error. Replicache client will retry forever until the server acks properly.

Another way to say all this is that the logical meaning of the events doesn't change but the code that interprets the events can change and will.

> the registry might be stored anywhere including in noms (?)

I'm not sure what it would mean to store the registry persistently. I think it's a feature that the registry is in-memory and the impls of the functions are just user code in the host language. But looking at the situations from `repm's` pov, yes, it doesn't know about the registry or its contents.

> the system supplied transactions .putvalue/.delvalue seem to exist to support command line transactions that dont have a registry to supply an implementation. they kind of complicate the mental model though: the bindings have to know to treat these special transactions differently from transactions they have registered and has to disallow transactions with these names. is there any way we could eliminate them so that all transactions are treated the same? like for example automatically register put/del as transactions in the registry? if command line put/del is important we could always require that the registry have those transactions and then continue to do them manually in the put/del command line implementation (create a Transaction and call put/del on it).

@arv is going to remove these in the next PR or so. See https://github.com/rocicorp/replicache/issues/27#issuecomment-611364369. There was also discussion about removing the features from `repm` in the last PR.

**Comment by aboodman** [comment]
>  there must exist a corresponding implementation by that name in the data layer

According to the current design, the "names" of the functions on the client and server are different. The "event" in the client-side log records both the local name/args and the remote name/args.

It's tempting to combine them, as it would simplify the API. There are two ways you could do it:

1. Keep only the existing "local" name/args. When we ship the tx's server-side the batch handler must then map the local names/args to server-side impls. Or client-side code must. Some code gets a teeny bit more complex and the promise that we use your existing endpoints gets eroded a little more.
2. Keep only the existing "remote" name/args. The registry of client-side impls becomes a registry of impls of server-side endpoints.
2b. A special case of 2 for GraphQL that is for the user code to provide a GraphQL "resolver" which operates against the local cache.

(1) Seems "easiest' and "simplest" from our perspective. But it creates some small amt of extra work for server-side dev. It's also an abstraction on top of what's going on that's not strictly necessary, which is a bit of a design smell to me. (Because it feels it could trivially be done a layer up by either user or us as a library).

(2) Is pretty tempting and clean but implies extra serialization and deserialization to call the client-side  impl in the case where the server-side impl uses a special encoding (e.g. protobufs).

I feel that 2b is the obvious way to do this for applications that use GraphQL and people will immediately write libraries that do this, and maybe they should even be at github.com/rocicorp and be maintained by us.

... but figuring out which is best of these or whether we should do any of them is beyond my current horizon, so I fall back to doing none and waiting to see what people want.

**Comment by phritz** [comment]
thanks for the explanations, really helpful. i'm going to assume that anything you don't comment on is generally the right idea.

re changing implementations: ack

re combining local remote names and args: guess i need to think about this more but if the assumption is that the endpoints exist then they already have code in their app to construct requests to it so 2 seems pretty natural. if the endpoints dont exist then as a developer i would probably err on the side of pushing complexity out of the app and into the server because it is under my control (i can updated it whenever i want, scale it, etc) - so i would probably go with 1. i agree that this does seem like a question that our customers will tell us the answer to.

assuming that we don't combine them right now (which i think is what you are suggesting as 'doing none', and seems good) then there is a thingy supplied by the customer that knows how to turn an event (transaction name + args) into a url and request body. This thingy in your sample code is their transaction implementation. ~In any case, when we execute their transaction and it commits with a successful write we record it in a queue to ship upstream. This queue lives in the client.~ ~Edit 1: We execute their transaction and if it commits with a successful write then we need to enqueue the event for shipping upstream. we have options for this: the top level branch seems like who keeps them. if the bindings keep them then they can pass them into sync. if we keep them in the client they could go into the commit or into a separate queue. or if the client can call into the bindings or we can make sync a two-step process (repmapi.GetPendingEvents(), repmapi.Sync([]requests, ...)) then nobody keeps them: we get the name and args out of the pending commits and have the user code generate the request at or just before sync time. need to think more about this, but presuming you have thought this through more than me.~ Edit 2: ah I am now piecing this all together. on the other issue you say "I think that we should try to keep the RPC protocol request/response based, implying that the way this has to work is that BeginSync() RPC does push and pull, then returns a list of tx names/args that need to be replayed. Then bindings do so, then call EndSync()." which makes a lot of sense. I get it now.

> promise that we use your existing endpoints gets eroded a little more.

do we have any information yet from potential customers about how important this actually is? we keep saying it and i'm curious how important it is in reality (like, i have no sense of it).

**Comment by aboodman** [comment]
> According to the current design, the "names" of the functions on the client and server are different. The "event" in the client-side log records both the local name/args and the remote name/args.

This part of my statement was wrong, sorry. The current design calls for us just to record the local name/args. The user code on the client translates them into a server RPC at runtime as sync is happening. (See the "overview" section of https://github.com/rocicorp/replicache/issues/28).

We could simplify the client-side bindings by removing this mapping procedure by just posting the local name/args to the server in the batch and letting the server sort it out.

It's just sort of pushing things from one place to another - I don't have a clear idea of which way users will prefer, or what is simpler.

> do we have any information yet from potential customers about how important this actually is? we keep saying it and i'm curious how important it is in reality (like, i have no sense of it).

Not really, and I don't think it's that big a deal.

I'm sort of coming to the conclusion it will be easier to post the local names/args in the batch and let the server sort it. It would certainly simplify the API client side which is nice.

**Comment by aboodman** [comment]
>> do we have any information yet from potential customers about how important this actually is? we keep saying it and i'm curious how important it is in reality (like, i have no sense of it).

> Not really, and I don't think it's that big a deal.

The motivation is more meta and based on concrete information that we do have: that it is crucial that people be able to use their existing stacks and infrastructure, and that integration be easy and incremental (you can try Replicache on just one feature or cohort at a time).

But whether you can reuse the actual existing endpoints doesn't have a big impact on that value, you are right.

**Comment by aboodman** [comment]
> I'm sort of coming to the conclusion it will be easier to post the local names/args in the batch and let the server sort it. It would certainly simplify the API client side which is nice.

Sorry on third thought, no so sure. There are tradeoffs here. Let's stick with the current design or if we're going to change it rethinking it a more deliberate way (like in the implementation sketch for this bug that I think you're working on).

**Comment by phritz** [comment]
> I'm sort of coming to the conclusion it will be easier to post the local names/args in the batch and let the server sort it. It would certainly simplify the API client side which is nice.

Yeah that would be nice and simple. It makes the server interface look like the local interface which is one less thing to keep in your head and it makes it really clear that we are invoking a transaction on the server.

**Comment by phritz** [comment]
> The current design calls for us just to record the local name/args. The user code on the client translates them into a server RPC at runtime as sync is happening. (See the "overview" section of #28).

I'd like to understand what you intend when you say that the the client translates them into an rpc at sync time. The way I understand sync works:
- app calls BeginSync, which pushes and pulls and returns the list of mutations to replay
- bindings replays mutations
- bindings calls endsync

If we are sending the local names and args in the push then we don't need anything else to push in beginsync: we have the names and args recorded in the pending commits. However that's not the plan, so we need the remote names/args in sync somehow. I'm not sure which of the following ways is intended (if any):
- Within BeginSync in the client we call into the bindings to translate local name/args to remote names/args; or
- In addition to the local names and args, the bindings passes the remote names and args to opentransaction and they are stored alongside the local ones in the Commit; or 
- Sync has an additional step: before calling beginsync the bindings call getpendingtransactions which returns the list of names/args of pending transactions. Then bindings translates those into remote names and args and passes them into the beginsync call. 

The first and third options send the args across the bindings boundary basically three times whereas the second option sends it across once at the cost of storage. The second option has fewer moving parts.

**Comment by aboodman** [comment]
Yeah we should talk about this in realtime.

**Comment by phritz** [comment]
Decision: 1 sounds scary and 3 sounds icky. Let's do 2 for now.

**Comment by aboodman** [comment]
Updated decision, we're going to kill the distinction between local and remote names/args and just send the local ones to the server as @phritz originally proposed. It is a lot conceptually simpler, and I realized we are already wed to json and have the coupling I was trying to avoid via the client view (@arv also pointed this out). Sorry it took me a few days to come around to this.

**Comment by aboodman** [comment]
I'd also like to take one of @arv's early suggestions for syntax sugar.

Updated combined syntax proposal:

```
// Register takes the name of a mutation and an optimistic implementation of that mutation that runs
// against the cache. The optimistic implementation might be called many times against different
// snapshots. The mutation name and args of each invocation will be passed to the batch endpoint
// as part of upstream sync.
//
// Note: Replicache may call mutations by name across app restarts. Registration should be done at
// startup, and once a name is used, it should continue to be defined forever and not change its
// meaning.
const createTodo = replicache.register("create-todo", (WriteTransaction tx, dynamic args) async {
  await tx.put("/todo/${args['id']}", args);
});

// Ah, nice and simple.
createTodo({'id': uuid.new(), 'title': 'Take out the trash', 'done': false});
```

**Comment by arv** [comment]
That API does not work. Darr has no support for variadic functions.
