### ISSUE TITLE
Prevent reentrancy in Flutter SDK

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-old#49]
A transaction should not be able to open another transaction. This can happen if the tx function references a Replicache object.

In a non async world this could be detected by checking the call stack. In an async world this can be done using [Zones](https://dart.dev/articles/archive/zones). Zones was also ported to Angular but it does require a bunch of monkey patches. See https://blog.strongbrew.io/how-the-hell-do-zones-really-work/

Maybe we can achieve this by passing around enough context to all the transactions?

**Comment by aboodman** [comment]
I don't see how we can do that and make it foolproof. If you do can you provide an example?

I definitely don't want to monkey-patch anything in a user's environment (*shivers remembering `onclick`).

IIRC the alternative to zones was to detect iloops trying to land transactions. You already created a bug for this. So if you implement that bug, then the zone thing is just a nicer dx on top of that in environments we can do it.

**Comment by arv** [comment]
> I don't see how we can do that and make it foolproof. If you do can you provide an example?

I don't know why I keep resetting my brain on this problem?

**Comment by aboodman** [comment]
On Tue, May 5, 2020 at 8:58 AM Erik Arvidsson <notifications@github.com>
wrote:

> I don't see how we can do that and make it foolproof. If you do can you
> provide an example?
>
> I don't know why I keep resetting my brain on this problem?
>

I mean maybe you're onto something. It's a hard one to think about. The
clearest I can state it is:

createTodo = replicache.registerMutator("create-todo", (tx, args) async {
  // I know - I'll just share code!
  // This iloops because updateTodo will land between createTodo starting
and stopping,
  // meaning that the basis changes, meaning that createTodo has to retry.
But the same thing
  // happens everytime, so it can never succeed.
  await updateTodo(args);
});

If you can think of some better way around this problem then limiting
retries or zones, hooray.
