### ISSUE TITLE
Should we require batch endpoint to "synchronously" process all mutations?

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-old#9]
Right now, in the client API sketch, we require users to "register" all transaction implementations by name. That is, users have to do:

```
replicache.register("plus", (tx, key, incr) {
  let val = db.get(key) || 0;
  val += incr;
  tx.put(key, val);
});
replicache.exec("plus", "foo", 42);
```

Rather than:

```
replicache.exec((tx) {
  let val = db.get("foo") || 0;
  val += 42;
  tx.put("foo", val);
});
```

Beyond the ergonomic improvement, the former also has a hidden additional complexity, because we also require that the set of named transaction implementations is relatively stable over time, even across app restarts: Replicache might need to replay a transaction that was initially executed on a previous session of the app. Users should ensure that when Replicache goes to find that tx impl, it can find it.

I *think* the only reason we need these named implementations in the first place, is because the sync protocol allows the batch endpoint to _accept_ a transaction without it subsequently being _visible_ in the client view. As a result, the client needs to maintain the pending transaction -- and be able to replay it -- indefinitely, even across restarts.

If instead, we required that the effects of a transaction sent to the batch endpoint were visible in the client view as soon as the batch returned indicating success, then we could use the simpler anonymous API. Because in that case we would only ever need to replay transactions in the case that they were executed while a sync was in progress, which cannot happen while the app is not running.

Also, if we made that change, it seems like clients could optionally avoid implementing the ClientVersion storage map in their backend, so long as they already had some idempotency mechanism that they could use instead.

Finally, It seems like this proposal is what people must already be doing. Because right now if an app makes a write via an API and then immediately makes a read, the backend already has to deal with the fact that caller is going to probably expect the change to be reflected. At least developers already have to think about this and make a choice. It doesn't seem like Replicache is changing anything.

So questions:

1. Am I getting this right?
2. Are there other tradeoffs I'm not considering?
3. Should we do this?

**Comment by phritz** [comment]
Initial gut instinct is that we should not do this. However I'd love to
talk about it more. Some considerations:

- this kind of solution would be relatively easy for only very simple
customers or those who had a very sophisticated cloud service as their
storage. Customers who are in the middle territory who for example are
running their own non-trivial storage back ends for example with
replication and message passing are going to have a hard time with this.

- my gut was that most customers are not necessarily going to assume that
the result of an API call is visible as soon as the call returns. I mean
even in simple cases like chat one would not necessarily expect that just
because a message was accepted it was visible. However my gut could easily
be wrong here and I'm speaking from my own experience which is having
rolled my own infrastructure in this department.

- Even if you do away with transaction names it seems like there needs to
be some kind of versioning that is passed from the client to the server and
even just used on the client to ensure that the schema or data model the
transaction is being executed against is what is intended. I had assumed
that version information will be baked into the transaction name and if not
seems like there needs to be some other mechanism. Not that this is a deal
breaker.

-putting my offline first hat on it seems more offliney to not require
synchronous API calls at the server. For example maybe you want to accept
all the work that you can and queue it so the client doesn't have to keep
retrying it.

- from a security perspective having a client under a potential adversaries
control be able to pass code / transaction to be executed inside my data
layer definitely makes me go hmm. I would feel more comfortable providing
the implementations myself. But again not a deal breaker just a bit of a
yellow flag.

- I do think the simplicity of not requiring the customer to keep the
mapping from client to transaction ID is appealing in that it lowers the
bar. I wonder if we should start there because it requires less on both the
client and the server and see How strong the demand is to accommodate
asynchronous API calls. I do worry however that requiring synchronous API
calls will lead potential customers to dismiss us as a solution out of hand.

**Comment by phritz** [comment]
note for somer reason part of my reply is hidden w/... above maybe because i responded in email? here's the full reply:

Initial gut instinct is that we should not do this. However I'd love to
talk about it more. Some considerations:

- this kind of solution would be relatively easy for only very simple
customers or those who had a very sophisticated cloud service as their
storage. Customers who are in the middle territory who for example are
running their own non-trivial storage back ends for example with
replication and message passing are going to have a hard time with this.

- my gut was that most customers are not necessarily going to assume that
the result of an API call is visible as soon as the call returns. I mean
even in simple cases like chat one would not necessarily expect that just
because a message was accepted it was visible. However my gut could easily
be wrong here and I'm speaking from my own experience which is having
rolled my own infrastructure in this department.

- Even if you do away with transaction names it seems like there needs to
be some kind of versioning that is passed from the client to the server and
even just used on the client to ensure that the schema or data model the
transaction is being executed against is what is intended. I had assumed
that version information will be baked into the transaction name and if not
seems like there needs to be some other mechanism. Not that this is a deal
breaker.

- putting my offline first hat on it seems more offliney to not require
synchronous API calls at the server. For example maybe you want to accept
all the work that you can and queue it so the client doesn't have to keep
retrying it.

- from a security perspective having a client under a potential adversaries
control be able to pass code / transaction to be executed inside my data
layer definitely makes me go hmm. I would feel more comfortable providing
the implementations myself. But again not a deal breaker just a bit of a
yellow flag.

- I do think the simplicity of not requiring the customer to keep the
mapping from client to transaction ID is appealing in that it lowers the
bar. I wonder if we should start there because it requires less on both the
client and the server and see How strong the demand is to accommodate
asynchronous API calls. I do worry however that requiring synchronous API
calls will lead potential customers to dismiss us as a solution out of hand.

**Comment by aboodman** [comment]
> from a security perspective having a client under a potential adversaries
control be able to pass code / transaction to be executed inside my data
layer definitely makes me go hmm. I would feel more comfortable providing
the implementations myself. But again not a deal breaker just a bit of a
yellow flag.

Ah, I think you're misunderstanding what I'm proposing. We're not passing code to the data layer here. I'm talking about the local implementation of transactions. The question is just, is that implementation named, so that it can be looked up by name at any time? Or is it simply an in-memory property of the pending transaction.

**Comment by phritz** [comment]
ah i did misunderstand. but points 1 2 4 and 6 are about the synchronous server endpoint and still stand. point 3 dunno... on the client you update the app and what do you do with transactions that are sitting there from the previous version if the data model has changed? let em error, have code that migrates them, whatever. i'm not sure having a named transaction on the client helps any. so tldr my concern is about a synchronous server endpoint, not about naming tx on the client which i can't see any pro or con to except that they are easier to identify in the pending queue if they have a name. shrug.

**Comment by aboodman** [comment]
> this kind of solution would be relatively easy for only very simple
customers or those who had a very sophisticated cloud service as their
storage. Customers who are in the middle territory who for example are
running their own non-trivial storage back ends for example with
replication and message passing are going to have a hard time with this.

> my gut was that most customers are not necessarily going to assume that
the result of an API call is visible as soon as the call returns. I mean
even in simple cases like chat one would not necessarily expect that just
because a message was accepted it was visible. However my gut could easily
be wrong here and I'm speaking from my own experience which is having
rolled my own infrastructure in this department.

Don't customers *already* have to reason about this? If I have a web application and I mark an issue closed or add a comment, then refresh the page, I expect to see the change. I don't see how Replicache changes anything.

For something like a chat app, I agree people are probably doing fancy stuff on the client, along the lines of what Replicache offers. But I don't feel that is common, precisely because what Replicache offers is hard to do.

> putting my offline first hat on it seems more offliney to not require
synchronous API calls at the server. For example maybe you want to accept
all the work that you can and queue it so the client doesn't have to keep
retrying it.

This part I agree with. I think it's a pretty neat feature that a replicache-enabled client actually allows you to weaken the consistency requirements of the server. That's powerful.

**Comment by phritz** [comment]
customers already have to think about it but their endpoints do not have to be synchronous.

for example if the service is message oriented then at scale almost certainly the endpoint is not synchronous. the endpoint is going to stick the message in a queue somewhere and a consumer is going to pick it up at some point and it is a non goal to have the endpoint know anything other than how to enqueue messages.

even for apps that have synchronous endpoints for user actions there is no guarantee that client view fetches can be made totally consistent with user actions. for example client view requests impose quote a load, could be way more load than whatever the normal backend can handle. so client view reads have to come from read replicas somewhere, which will lag the canonical backend.

or perhaps the app uses a weakly consistent cloud storage backend. client view reads might not see the state just written. 

i think i need more information about our potential customers to know whether this is a problem. maybe there are enough folks for whom this is not a problem, but seems safest to require the latest tx to ride along with the data so you can tell where the client view is in time. if we have it the client should refuse to go back in time, which is a case i hadn't thought of before this discussion so yay.

**Comment by aboodman** [comment]
Hmm. This is interesting. Let me think about it a little more. Tempting to
simplify and wait for customers to tell us to complexity.

**Comment by phritz** [comment]
cool. obv add it to your list of customer questions: how they would have to implement client view on the server knowing that it is expensive in the ways that it is and ask if there might be inconsistency with just applied on the server transactions, eg if it could lag or go back in time.

**Comment by aboodman** [comment]
We decided after talking in person to leave it asynchronous.

@phritz thinks it will be difficult to implement an async API on top of the sync API because the batch endpoint would need to be able agree with the client view endpoint as to what the highest processed txid was.

I also realized separately that you can actually implement the client-side API I was envisioning on top of the async batch endpoint, using a similar hack (the client just refuses to reveal new states from teh server until they include all pending transactions for which the client does _not_ have an implementation).

So those two problems are decoupled now. Yay.
